// source: leilao.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.leilao.CancelarInteresseRequest', null, global);
goog.exportSymbol('proto.leilao.CancelarInteresseResponse', null, global);
goog.exportSymbol('proto.leilao.CriarLeilaoRequest', null, global);
goog.exportSymbol('proto.leilao.CriarLeilaoResponse', null, global);
goog.exportSymbol('proto.leilao.Leilao', null, global);
goog.exportSymbol('proto.leilao.ListarLeiloesRequest', null, global);
goog.exportSymbol('proto.leilao.ListarLeiloesResponse', null, global);
goog.exportSymbol('proto.leilao.NotificacaoLeilao', null, global);
goog.exportSymbol('proto.leilao.RegistrarInteresseRequest', null, global);
goog.exportSymbol('proto.leilao.RegistrarInteresseResponse', null, global);
goog.exportSymbol('proto.leilao.StreamNotificacoesRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.leilao.Leilao = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.leilao.Leilao, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.leilao.Leilao.displayName = 'proto.leilao.Leilao';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.leilao.CriarLeilaoRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.leilao.CriarLeilaoRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.leilao.CriarLeilaoRequest.displayName = 'proto.leilao.CriarLeilaoRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.leilao.CriarLeilaoResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.leilao.CriarLeilaoResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.leilao.CriarLeilaoResponse.displayName = 'proto.leilao.CriarLeilaoResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.leilao.ListarLeiloesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.leilao.ListarLeiloesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.leilao.ListarLeiloesRequest.displayName = 'proto.leilao.ListarLeiloesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.leilao.ListarLeiloesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.leilao.ListarLeiloesResponse.repeatedFields_, null);
};
goog.inherits(proto.leilao.ListarLeiloesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.leilao.ListarLeiloesResponse.displayName = 'proto.leilao.ListarLeiloesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.leilao.RegistrarInteresseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.leilao.RegistrarInteresseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.leilao.RegistrarInteresseRequest.displayName = 'proto.leilao.RegistrarInteresseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.leilao.RegistrarInteresseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.leilao.RegistrarInteresseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.leilao.RegistrarInteresseResponse.displayName = 'proto.leilao.RegistrarInteresseResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.leilao.CancelarInteresseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.leilao.CancelarInteresseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.leilao.CancelarInteresseRequest.displayName = 'proto.leilao.CancelarInteresseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.leilao.CancelarInteresseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.leilao.CancelarInteresseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.leilao.CancelarInteresseResponse.displayName = 'proto.leilao.CancelarInteresseResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.leilao.NotificacaoLeilao = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.leilao.NotificacaoLeilao, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.leilao.NotificacaoLeilao.displayName = 'proto.leilao.NotificacaoLeilao';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.leilao.StreamNotificacoesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.leilao.StreamNotificacoesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.leilao.StreamNotificacoesRequest.displayName = 'proto.leilao.StreamNotificacoesRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.leilao.Leilao.prototype.toObject = function(opt_includeInstance) {
  return proto.leilao.Leilao.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.leilao.Leilao} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.Leilao.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, 0),
nome: jspb.Message.getFieldWithDefault(msg, 2, ""),
descricao: jspb.Message.getFieldWithDefault(msg, 3, ""),
valorInicial: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
inicio: jspb.Message.getFieldWithDefault(msg, 5, ""),
fim: jspb.Message.getFieldWithDefault(msg, 6, ""),
status: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.leilao.Leilao}
 */
proto.leilao.Leilao.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.leilao.Leilao;
  return proto.leilao.Leilao.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.leilao.Leilao} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.leilao.Leilao}
 */
proto.leilao.Leilao.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNome(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescricao(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValorInicial(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setInicio(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setFim(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.leilao.Leilao.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.leilao.Leilao.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.leilao.Leilao} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.Leilao.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getNome();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescricao();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getValorInicial();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getInicio();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getFim();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.leilao.Leilao.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.leilao.Leilao} returns this
 */
proto.leilao.Leilao.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string nome = 2;
 * @return {string}
 */
proto.leilao.Leilao.prototype.getNome = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.Leilao} returns this
 */
proto.leilao.Leilao.prototype.setNome = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string descricao = 3;
 * @return {string}
 */
proto.leilao.Leilao.prototype.getDescricao = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.Leilao} returns this
 */
proto.leilao.Leilao.prototype.setDescricao = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional double valor_inicial = 4;
 * @return {number}
 */
proto.leilao.Leilao.prototype.getValorInicial = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.leilao.Leilao} returns this
 */
proto.leilao.Leilao.prototype.setValorInicial = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional string inicio = 5;
 * @return {string}
 */
proto.leilao.Leilao.prototype.getInicio = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.Leilao} returns this
 */
proto.leilao.Leilao.prototype.setInicio = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string fim = 6;
 * @return {string}
 */
proto.leilao.Leilao.prototype.getFim = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.Leilao} returns this
 */
proto.leilao.Leilao.prototype.setFim = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string status = 7;
 * @return {string}
 */
proto.leilao.Leilao.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.Leilao} returns this
 */
proto.leilao.Leilao.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.leilao.CriarLeilaoRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.leilao.CriarLeilaoRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.leilao.CriarLeilaoRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.CriarLeilaoRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
nome: jspb.Message.getFieldWithDefault(msg, 1, ""),
descricao: jspb.Message.getFieldWithDefault(msg, 2, ""),
valorInicial: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
inicio: jspb.Message.getFieldWithDefault(msg, 4, ""),
fim: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.leilao.CriarLeilaoRequest}
 */
proto.leilao.CriarLeilaoRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.leilao.CriarLeilaoRequest;
  return proto.leilao.CriarLeilaoRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.leilao.CriarLeilaoRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.leilao.CriarLeilaoRequest}
 */
proto.leilao.CriarLeilaoRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNome(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescricao(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValorInicial(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setInicio(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setFim(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.leilao.CriarLeilaoRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.leilao.CriarLeilaoRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.leilao.CriarLeilaoRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.CriarLeilaoRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNome();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescricao();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getValorInicial();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getInicio();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getFim();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string nome = 1;
 * @return {string}
 */
proto.leilao.CriarLeilaoRequest.prototype.getNome = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.CriarLeilaoRequest} returns this
 */
proto.leilao.CriarLeilaoRequest.prototype.setNome = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string descricao = 2;
 * @return {string}
 */
proto.leilao.CriarLeilaoRequest.prototype.getDescricao = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.CriarLeilaoRequest} returns this
 */
proto.leilao.CriarLeilaoRequest.prototype.setDescricao = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional double valor_inicial = 3;
 * @return {number}
 */
proto.leilao.CriarLeilaoRequest.prototype.getValorInicial = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.leilao.CriarLeilaoRequest} returns this
 */
proto.leilao.CriarLeilaoRequest.prototype.setValorInicial = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional string inicio = 4;
 * @return {string}
 */
proto.leilao.CriarLeilaoRequest.prototype.getInicio = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.CriarLeilaoRequest} returns this
 */
proto.leilao.CriarLeilaoRequest.prototype.setInicio = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string fim = 5;
 * @return {string}
 */
proto.leilao.CriarLeilaoRequest.prototype.getFim = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.CriarLeilaoRequest} returns this
 */
proto.leilao.CriarLeilaoRequest.prototype.setFim = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.leilao.CriarLeilaoResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.leilao.CriarLeilaoResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.leilao.CriarLeilaoResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.CriarLeilaoResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
success: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
message: jspb.Message.getFieldWithDefault(msg, 2, ""),
leilaoId: jspb.Message.getFieldWithDefault(msg, 3, 0),
leilao: (f = msg.getLeilao()) && proto.leilao.Leilao.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.leilao.CriarLeilaoResponse}
 */
proto.leilao.CriarLeilaoResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.leilao.CriarLeilaoResponse;
  return proto.leilao.CriarLeilaoResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.leilao.CriarLeilaoResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.leilao.CriarLeilaoResponse}
 */
proto.leilao.CriarLeilaoResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLeilaoId(value);
      break;
    case 4:
      var value = new proto.leilao.Leilao;
      reader.readMessage(value,proto.leilao.Leilao.deserializeBinaryFromReader);
      msg.setLeilao(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.leilao.CriarLeilaoResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.leilao.CriarLeilaoResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.leilao.CriarLeilaoResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.CriarLeilaoResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLeilaoId();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getLeilao();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.leilao.Leilao.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool success = 1;
 * @return {boolean}
 */
proto.leilao.CriarLeilaoResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.leilao.CriarLeilaoResponse} returns this
 */
proto.leilao.CriarLeilaoResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.leilao.CriarLeilaoResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.CriarLeilaoResponse} returns this
 */
proto.leilao.CriarLeilaoResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 leilao_id = 3;
 * @return {number}
 */
proto.leilao.CriarLeilaoResponse.prototype.getLeilaoId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.leilao.CriarLeilaoResponse} returns this
 */
proto.leilao.CriarLeilaoResponse.prototype.setLeilaoId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional Leilao leilao = 4;
 * @return {?proto.leilao.Leilao}
 */
proto.leilao.CriarLeilaoResponse.prototype.getLeilao = function() {
  return /** @type{?proto.leilao.Leilao} */ (
    jspb.Message.getWrapperField(this, proto.leilao.Leilao, 4));
};


/**
 * @param {?proto.leilao.Leilao|undefined} value
 * @return {!proto.leilao.CriarLeilaoResponse} returns this
*/
proto.leilao.CriarLeilaoResponse.prototype.setLeilao = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.leilao.CriarLeilaoResponse} returns this
 */
proto.leilao.CriarLeilaoResponse.prototype.clearLeilao = function() {
  return this.setLeilao(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.leilao.CriarLeilaoResponse.prototype.hasLeilao = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.leilao.ListarLeiloesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.leilao.ListarLeiloesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.leilao.ListarLeiloesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.ListarLeiloesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.leilao.ListarLeiloesRequest}
 */
proto.leilao.ListarLeiloesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.leilao.ListarLeiloesRequest;
  return proto.leilao.ListarLeiloesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.leilao.ListarLeiloesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.leilao.ListarLeiloesRequest}
 */
proto.leilao.ListarLeiloesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.leilao.ListarLeiloesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.leilao.ListarLeiloesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.leilao.ListarLeiloesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.ListarLeiloesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.leilao.ListarLeiloesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.leilao.ListarLeiloesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.leilao.ListarLeiloesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.leilao.ListarLeiloesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.ListarLeiloesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
leiloesList: jspb.Message.toObjectList(msg.getLeiloesList(),
    proto.leilao.Leilao.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.leilao.ListarLeiloesResponse}
 */
proto.leilao.ListarLeiloesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.leilao.ListarLeiloesResponse;
  return proto.leilao.ListarLeiloesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.leilao.ListarLeiloesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.leilao.ListarLeiloesResponse}
 */
proto.leilao.ListarLeiloesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.leilao.Leilao;
      reader.readMessage(value,proto.leilao.Leilao.deserializeBinaryFromReader);
      msg.addLeiloes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.leilao.ListarLeiloesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.leilao.ListarLeiloesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.leilao.ListarLeiloesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.ListarLeiloesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLeiloesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.leilao.Leilao.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Leilao leiloes = 1;
 * @return {!Array<!proto.leilao.Leilao>}
 */
proto.leilao.ListarLeiloesResponse.prototype.getLeiloesList = function() {
  return /** @type{!Array<!proto.leilao.Leilao>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.leilao.Leilao, 1));
};


/**
 * @param {!Array<!proto.leilao.Leilao>} value
 * @return {!proto.leilao.ListarLeiloesResponse} returns this
*/
proto.leilao.ListarLeiloesResponse.prototype.setLeiloesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.leilao.Leilao=} opt_value
 * @param {number=} opt_index
 * @return {!proto.leilao.Leilao}
 */
proto.leilao.ListarLeiloesResponse.prototype.addLeiloes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.leilao.Leilao, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.leilao.ListarLeiloesResponse} returns this
 */
proto.leilao.ListarLeiloesResponse.prototype.clearLeiloesList = function() {
  return this.setLeiloesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.leilao.RegistrarInteresseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.leilao.RegistrarInteresseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.leilao.RegistrarInteresseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.RegistrarInteresseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
leilaoId: jspb.Message.getFieldWithDefault(msg, 1, 0),
clienteId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.leilao.RegistrarInteresseRequest}
 */
proto.leilao.RegistrarInteresseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.leilao.RegistrarInteresseRequest;
  return proto.leilao.RegistrarInteresseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.leilao.RegistrarInteresseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.leilao.RegistrarInteresseRequest}
 */
proto.leilao.RegistrarInteresseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLeilaoId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setClienteId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.leilao.RegistrarInteresseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.leilao.RegistrarInteresseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.leilao.RegistrarInteresseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.RegistrarInteresseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLeilaoId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getClienteId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 leilao_id = 1;
 * @return {number}
 */
proto.leilao.RegistrarInteresseRequest.prototype.getLeilaoId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.leilao.RegistrarInteresseRequest} returns this
 */
proto.leilao.RegistrarInteresseRequest.prototype.setLeilaoId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string cliente_id = 2;
 * @return {string}
 */
proto.leilao.RegistrarInteresseRequest.prototype.getClienteId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.RegistrarInteresseRequest} returns this
 */
proto.leilao.RegistrarInteresseRequest.prototype.setClienteId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.leilao.RegistrarInteresseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.leilao.RegistrarInteresseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.leilao.RegistrarInteresseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.RegistrarInteresseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
success: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.leilao.RegistrarInteresseResponse}
 */
proto.leilao.RegistrarInteresseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.leilao.RegistrarInteresseResponse;
  return proto.leilao.RegistrarInteresseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.leilao.RegistrarInteresseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.leilao.RegistrarInteresseResponse}
 */
proto.leilao.RegistrarInteresseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.leilao.RegistrarInteresseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.leilao.RegistrarInteresseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.leilao.RegistrarInteresseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.RegistrarInteresseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bool success = 1;
 * @return {boolean}
 */
proto.leilao.RegistrarInteresseResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.leilao.RegistrarInteresseResponse} returns this
 */
proto.leilao.RegistrarInteresseResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.leilao.RegistrarInteresseResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.RegistrarInteresseResponse} returns this
 */
proto.leilao.RegistrarInteresseResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.leilao.CancelarInteresseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.leilao.CancelarInteresseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.leilao.CancelarInteresseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.CancelarInteresseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
leilaoId: jspb.Message.getFieldWithDefault(msg, 1, 0),
clienteId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.leilao.CancelarInteresseRequest}
 */
proto.leilao.CancelarInteresseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.leilao.CancelarInteresseRequest;
  return proto.leilao.CancelarInteresseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.leilao.CancelarInteresseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.leilao.CancelarInteresseRequest}
 */
proto.leilao.CancelarInteresseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLeilaoId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setClienteId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.leilao.CancelarInteresseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.leilao.CancelarInteresseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.leilao.CancelarInteresseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.CancelarInteresseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLeilaoId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getClienteId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 leilao_id = 1;
 * @return {number}
 */
proto.leilao.CancelarInteresseRequest.prototype.getLeilaoId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.leilao.CancelarInteresseRequest} returns this
 */
proto.leilao.CancelarInteresseRequest.prototype.setLeilaoId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string cliente_id = 2;
 * @return {string}
 */
proto.leilao.CancelarInteresseRequest.prototype.getClienteId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.CancelarInteresseRequest} returns this
 */
proto.leilao.CancelarInteresseRequest.prototype.setClienteId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.leilao.CancelarInteresseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.leilao.CancelarInteresseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.leilao.CancelarInteresseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.CancelarInteresseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
success: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.leilao.CancelarInteresseResponse}
 */
proto.leilao.CancelarInteresseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.leilao.CancelarInteresseResponse;
  return proto.leilao.CancelarInteresseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.leilao.CancelarInteresseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.leilao.CancelarInteresseResponse}
 */
proto.leilao.CancelarInteresseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.leilao.CancelarInteresseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.leilao.CancelarInteresseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.leilao.CancelarInteresseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.CancelarInteresseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bool success = 1;
 * @return {boolean}
 */
proto.leilao.CancelarInteresseResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.leilao.CancelarInteresseResponse} returns this
 */
proto.leilao.CancelarInteresseResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.leilao.CancelarInteresseResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.CancelarInteresseResponse} returns this
 */
proto.leilao.CancelarInteresseResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.leilao.NotificacaoLeilao.prototype.toObject = function(opt_includeInstance) {
  return proto.leilao.NotificacaoLeilao.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.leilao.NotificacaoLeilao} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.NotificacaoLeilao.toObject = function(includeInstance, msg) {
  var f, obj = {
tipo: jspb.Message.getFieldWithDefault(msg, 1, ""),
leilaoId: jspb.Message.getFieldWithDefault(msg, 2, 0),
leilao: (f = msg.getLeilao()) && proto.leilao.Leilao.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.leilao.NotificacaoLeilao}
 */
proto.leilao.NotificacaoLeilao.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.leilao.NotificacaoLeilao;
  return proto.leilao.NotificacaoLeilao.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.leilao.NotificacaoLeilao} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.leilao.NotificacaoLeilao}
 */
proto.leilao.NotificacaoLeilao.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTipo(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLeilaoId(value);
      break;
    case 3:
      var value = new proto.leilao.Leilao;
      reader.readMessage(value,proto.leilao.Leilao.deserializeBinaryFromReader);
      msg.setLeilao(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.leilao.NotificacaoLeilao.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.leilao.NotificacaoLeilao.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.leilao.NotificacaoLeilao} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.NotificacaoLeilao.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTipo();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLeilaoId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getLeilao();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.leilao.Leilao.serializeBinaryToWriter
    );
  }
};


/**
 * optional string tipo = 1;
 * @return {string}
 */
proto.leilao.NotificacaoLeilao.prototype.getTipo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.NotificacaoLeilao} returns this
 */
proto.leilao.NotificacaoLeilao.prototype.setTipo = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 leilao_id = 2;
 * @return {number}
 */
proto.leilao.NotificacaoLeilao.prototype.getLeilaoId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.leilao.NotificacaoLeilao} returns this
 */
proto.leilao.NotificacaoLeilao.prototype.setLeilaoId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional Leilao leilao = 3;
 * @return {?proto.leilao.Leilao}
 */
proto.leilao.NotificacaoLeilao.prototype.getLeilao = function() {
  return /** @type{?proto.leilao.Leilao} */ (
    jspb.Message.getWrapperField(this, proto.leilao.Leilao, 3));
};


/**
 * @param {?proto.leilao.Leilao|undefined} value
 * @return {!proto.leilao.NotificacaoLeilao} returns this
*/
proto.leilao.NotificacaoLeilao.prototype.setLeilao = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.leilao.NotificacaoLeilao} returns this
 */
proto.leilao.NotificacaoLeilao.prototype.clearLeilao = function() {
  return this.setLeilao(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.leilao.NotificacaoLeilao.prototype.hasLeilao = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.leilao.StreamNotificacoesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.leilao.StreamNotificacoesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.leilao.StreamNotificacoesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.StreamNotificacoesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
clienteId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.leilao.StreamNotificacoesRequest}
 */
proto.leilao.StreamNotificacoesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.leilao.StreamNotificacoesRequest;
  return proto.leilao.StreamNotificacoesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.leilao.StreamNotificacoesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.leilao.StreamNotificacoesRequest}
 */
proto.leilao.StreamNotificacoesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClienteId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.leilao.StreamNotificacoesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.leilao.StreamNotificacoesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.leilao.StreamNotificacoesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leilao.StreamNotificacoesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClienteId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string cliente_id = 1;
 * @return {string}
 */
proto.leilao.StreamNotificacoesRequest.prototype.getClienteId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.leilao.StreamNotificacoesRequest} returns this
 */
proto.leilao.StreamNotificacoesRequest.prototype.setClienteId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.leilao);
