/**
 * @fileoverview gRPC-Web generated client stub for leilao
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.1
// source: leilao.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.leilao = require('./leilao_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.leilao.LeilaoServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.leilao.LeilaoServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.leilao.CriarLeilaoRequest,
 *   !proto.leilao.CriarLeilaoResponse>}
 */
const methodDescriptor_LeilaoService_CriarLeilao = new grpc.web.MethodDescriptor(
  '/leilao.LeilaoService/CriarLeilao',
  grpc.web.MethodType.UNARY,
  proto.leilao.CriarLeilaoRequest,
  proto.leilao.CriarLeilaoResponse,
  /**
   * @param {!proto.leilao.CriarLeilaoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.leilao.CriarLeilaoResponse.deserializeBinary
);


/**
 * @param {!proto.leilao.CriarLeilaoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.leilao.CriarLeilaoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.leilao.CriarLeilaoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.leilao.LeilaoServiceClient.prototype.criarLeilao =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/leilao.LeilaoService/CriarLeilao',
      request,
      metadata || {},
      methodDescriptor_LeilaoService_CriarLeilao,
      callback);
};


/**
 * @param {!proto.leilao.CriarLeilaoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.leilao.CriarLeilaoResponse>}
 *     Promise that resolves to the response
 */
proto.leilao.LeilaoServicePromiseClient.prototype.criarLeilao =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/leilao.LeilaoService/CriarLeilao',
      request,
      metadata || {},
      methodDescriptor_LeilaoService_CriarLeilao);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.leilao.ListarLeiloesRequest,
 *   !proto.leilao.ListarLeiloesResponse>}
 */
const methodDescriptor_LeilaoService_ListarLeiloes = new grpc.web.MethodDescriptor(
  '/leilao.LeilaoService/ListarLeiloes',
  grpc.web.MethodType.UNARY,
  proto.leilao.ListarLeiloesRequest,
  proto.leilao.ListarLeiloesResponse,
  /**
   * @param {!proto.leilao.ListarLeiloesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.leilao.ListarLeiloesResponse.deserializeBinary
);


/**
 * @param {!proto.leilao.ListarLeiloesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.leilao.ListarLeiloesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.leilao.ListarLeiloesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.leilao.LeilaoServiceClient.prototype.listarLeiloes =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/leilao.LeilaoService/ListarLeiloes',
      request,
      metadata || {},
      methodDescriptor_LeilaoService_ListarLeiloes,
      callback);
};


/**
 * @param {!proto.leilao.ListarLeiloesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.leilao.ListarLeiloesResponse>}
 *     Promise that resolves to the response
 */
proto.leilao.LeilaoServicePromiseClient.prototype.listarLeiloes =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/leilao.LeilaoService/ListarLeiloes',
      request,
      metadata || {},
      methodDescriptor_LeilaoService_ListarLeiloes);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.leilao.RegistrarInteresseRequest,
 *   !proto.leilao.RegistrarInteresseResponse>}
 */
const methodDescriptor_LeilaoService_RegistrarInteresse = new grpc.web.MethodDescriptor(
  '/leilao.LeilaoService/RegistrarInteresse',
  grpc.web.MethodType.UNARY,
  proto.leilao.RegistrarInteresseRequest,
  proto.leilao.RegistrarInteresseResponse,
  /**
   * @param {!proto.leilao.RegistrarInteresseRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.leilao.RegistrarInteresseResponse.deserializeBinary
);


/**
 * @param {!proto.leilao.RegistrarInteresseRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.leilao.RegistrarInteresseResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.leilao.RegistrarInteresseResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.leilao.LeilaoServiceClient.prototype.registrarInteresse =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/leilao.LeilaoService/RegistrarInteresse',
      request,
      metadata || {},
      methodDescriptor_LeilaoService_RegistrarInteresse,
      callback);
};


/**
 * @param {!proto.leilao.RegistrarInteresseRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.leilao.RegistrarInteresseResponse>}
 *     Promise that resolves to the response
 */
proto.leilao.LeilaoServicePromiseClient.prototype.registrarInteresse =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/leilao.LeilaoService/RegistrarInteresse',
      request,
      metadata || {},
      methodDescriptor_LeilaoService_RegistrarInteresse);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.leilao.CancelarInteresseRequest,
 *   !proto.leilao.CancelarInteresseResponse>}
 */
const methodDescriptor_LeilaoService_CancelarInteresse = new grpc.web.MethodDescriptor(
  '/leilao.LeilaoService/CancelarInteresse',
  grpc.web.MethodType.UNARY,
  proto.leilao.CancelarInteresseRequest,
  proto.leilao.CancelarInteresseResponse,
  /**
   * @param {!proto.leilao.CancelarInteresseRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.leilao.CancelarInteresseResponse.deserializeBinary
);


/**
 * @param {!proto.leilao.CancelarInteresseRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.leilao.CancelarInteresseResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.leilao.CancelarInteresseResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.leilao.LeilaoServiceClient.prototype.cancelarInteresse =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/leilao.LeilaoService/CancelarInteresse',
      request,
      metadata || {},
      methodDescriptor_LeilaoService_CancelarInteresse,
      callback);
};


/**
 * @param {!proto.leilao.CancelarInteresseRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.leilao.CancelarInteresseResponse>}
 *     Promise that resolves to the response
 */
proto.leilao.LeilaoServicePromiseClient.prototype.cancelarInteresse =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/leilao.LeilaoService/CancelarInteresse',
      request,
      metadata || {},
      methodDescriptor_LeilaoService_CancelarInteresse);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.leilao.StreamNotificacoesRequest,
 *   !proto.leilao.NotificacaoLeilao>}
 */
const methodDescriptor_LeilaoService_StreamNotificacoes = new grpc.web.MethodDescriptor(
  '/leilao.LeilaoService/StreamNotificacoes',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.leilao.StreamNotificacoesRequest,
  proto.leilao.NotificacaoLeilao,
  /**
   * @param {!proto.leilao.StreamNotificacoesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.leilao.NotificacaoLeilao.deserializeBinary
);


/**
 * @param {!proto.leilao.StreamNotificacoesRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.leilao.NotificacaoLeilao>}
 *     The XHR Node Readable Stream
 */
proto.leilao.LeilaoServiceClient.prototype.streamNotificacoes =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/leilao.LeilaoService/StreamNotificacoes',
      request,
      metadata || {},
      methodDescriptor_LeilaoService_StreamNotificacoes);
};


/**
 * @param {!proto.leilao.StreamNotificacoesRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.leilao.NotificacaoLeilao>}
 *     The XHR Node Readable Stream
 */
proto.leilao.LeilaoServicePromiseClient.prototype.streamNotificacoes =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/leilao.LeilaoService/StreamNotificacoes',
      request,
      metadata || {},
      methodDescriptor_LeilaoService_StreamNotificacoes);
};


module.exports = proto.leilao;

