# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import leilao_pb2 as leilao__pb2
import lance_pb2 as lance__pb2
import pagamento_pb2 as pagamento__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x07gateway\x1a\x0cleilao.proto\x1a\x0blance.proto\x1a\x0fpagamento.proto\"\xc5\x01\n\x14NotificacaoUnificada\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x11\n\tleilao_id\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\r\n\x05valor\x18\x04 \x01(\x01\x12\x13\n\x0bid_vencedor\x18\x05 \x01(\t\x12\x16\n\x0elink_pagamento\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x0f\n\x07message\x18\x08 \x01(\t\x12\x1e\n\x06leilao\x18\t \x01(\x0b\x32\x0e.leilao.Leilao\"9\n#StreamNotificacoesUnificadasRequest\x12\x12\n\ncliente_id\x18\x01 \x01(\t2\xf5\x04\n\x0eGatewayService\x12\x46\n\x0b\x43riarLeilao\x12\x1a.leilao.CriarLeilaoRequest\x1a\x1b.leilao.CriarLeilaoResponse\x12L\n\rListarLeiloes\x12\x1c.leilao.ListarLeiloesRequest\x1a\x1d.leilao.ListarLeiloesResponse\x12[\n\x12RegistrarInteresse\x12!.leilao.RegistrarInteresseRequest\x1a\".leilao.RegistrarInteresseResponse\x12X\n\x11\x43\x61ncelarInteresse\x12 .leilao.CancelarInteresseRequest\x1a!.leilao.CancelarInteresseResponse\x12\x44\n\x0b\x45nviarLance\x12\x19.lance.EnviarLanceRequest\x1a\x1a.lance.EnviarLanceResponse\x12\x61\n\x12ProcessarPagamento\x12$.pagamento.ProcessarPagamentoRequest\x1a%.pagamento.ProcessarPagamentoResponse\x12m\n\x1cStreamNotificacoesUnificadas\x12,.gateway.StreamNotificacoesUnificadasRequest\x1a\x1d.gateway.NotificacaoUnificada0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICACAOUNIFICADA']._serialized_start=71
  _globals['_NOTIFICACAOUNIFICADA']._serialized_end=268
  _globals['_STREAMNOTIFICACOESUNIFICADASREQUEST']._serialized_start=270
  _globals['_STREAMNOTIFICACOESUNIFICADASREQUEST']._serialized_end=327
  _globals['_GATEWAYSERVICE']._serialized_start=330
  _globals['_GATEWAYSERVICE']._serialized_end=959
# @@protoc_insertion_point(module_scope)
